version: '3'
services:
  backend:
    command: npm run dev
    depends_on:
      - database
    environment:
      DATABASE_HOST: database
    image: node:16
    expose:
      - 1337
    volumes:
      - ./backend:/home/node/app
    working_dir: /home/node/app
  database:
    image: postgres
    environment:
      POSTGRES_DB: clipping-service
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    expose:
      - 5432
    volumes:
      - database:/var/lib/postgresql/data
  nginx:
    command: bash -c '/test-endpoint.sh backend 1337 && echo "Starting NGiNX..." && nginx -g "daemon off;"'
    image: nginx
    ports:
      - 9001:80
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./scripts/test-endpoint.sh:/test-endpoint.sh
volumes:
  database:
    driver: local
