version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - database
    env_file: ./backend/.env
    environment:
      DATABASE_HOST: database
      NODE_ENV: production
    expose:
      - 1337
    volumes:
      - ${PLEX_DIR}:/home/node/app/media
      - ./backend/clips:/home/node/app/clips
      - ./backend/uploads:/home/node/app/uploads
    working_dir: /home/node/app
  database:
    environment:
      POSTGRES_DB: clipping-service
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    expose:
      - 5432
    image: postgres
    volumes:
      - database:/var/lib/postgresql/data
  frontend:
    build:
      context: ./frontend
    depends_on:
      backend:
        condition: service_healthy
    environment:
      GIT_COMMIT: ${GIT_COMMIT}
    expose:
      - 3000
    working_dir: /home/node/app
  nginx:
    command: nginx -g "daemon off;"
    depends_on:
      backend:
        condition: service_healthy
      frontend:
        condition: service_started
    image: nginx
    ports:
      - ${PORT:-9001}:80
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
volumes:
  database:
    driver: local
