version: '3'
services:
  backend:
    command: bash -c 'npm run build && npm run start'
    depends_on:
      - database
    env_file: ./config/production.backend.env
    environment:
      DATABASE_HOST: database
      NODE_ENV: production
    image: node:16
    expose:
      - 1337
    volumes:
      - ${PLEX_DIR}:/home/node/app/media
      - ./backend:/home/node/app
    working_dir: /home/node/app
  database:
    image: postgres
    environment:
      POSTGRES_DB: clipping-service
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    expose:
      - 5432
    volumes:
      - database:/var/lib/postgresql/data
  frontend:
    command: bash -c '/test-endpoint.sh backend 1337 && npm run build && npm run start'
    depends_on:
      - backend
    env_file: ./config/production.frontend.env
    image: node:16
    expose:
      - 3000
    volumes:
      - ./frontend:/home/node/app
      - ./scripts/test-endpoint.sh:/test-endpoint.sh
    working_dir: /home/node/app
  nginx:
    command: bash -c '/test-endpoint.sh backend 1337 && echo "Starting NGiNX..." && nginx -g "daemon off;"'
    depends_on:
      - frontend
    image: nginx
    ports:
      - 9001:80
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./scripts/test-endpoint.sh:/test-endpoint.sh
volumes:
  database:
    driver: local
